name: nlp_techdoc_venv

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.8
  - pip
  - pip:
#NLP libraries:
    - pandas==1.3.4
    - numpy==1.20.3
    - cachetools==5.0.0
    - nltk
    - textblob
    - ipykernel
    - beautifulsoup4
    - datasets==2.0.0
    - demoji
    - decorator
    - huggingface-hub==0.5.1
    - transformers==4.18.0
    - keras==2.8.0
    - keras-preprocessing==1.1.2
    - markdown
    - notebook==6.4.10
    - jupyter-core==4.9.2
    - jupyter-client==7.1.2
    - pyarrow==7.0.0
    - pyyaml
    - scipy
    - tensorflow==2.8.0
    - torch==1.11.0
    - tokenizers
    - gensim
    - CoreNLP
    - spacy==3.2.3
    - pattern
    - bertopic[gensim]
    - Scattertext
    - LDA
    - Texthero
    - polyglot
    - allennlp
    - scikit-learn==0.24.2
    - matplotlib
    - plotly
    - seaborn







